language: generic

sudo: required

services:
  - docker

# before_install:
#   - docker build -t makkii/react-test -f ./client/Dockerfile.dev .

# script:
#   - docker run -e CI=true makkii/react-test npm test

after_success:
  - docker logout
  - docker build -t makkii/multi-client ./client
  - docker build -t makkii/multi-nginx ./nginx
  - docker build -t makkii/multi-server ./server
  - docker build -t makkii/multi-worker ./worker
  # Login to docker CLI
  # - $echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login --username "$DOCKER_ID" --password "$DOCKER_PASSWORD"
  # Take those images and push to docker hub
  - docker push makkii/multi-client
  - docker push makkii/multi-nginx
  - docker push makkii/multi-server
  - docker push makkii/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-687671861317'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
